In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
# loading the data from csv file to a Panda Dataframe
data = pd.read_excel('evade.xlsx', index_col=0)

# printing the first 5 rows of the dataframe
data.head()

Refund  Marital_Status  Taxable_Income  Evade
Tid                                               
1         1               0          125000      0
2         0               1          100000      0
3         0               0           70000      0
4         1               1          120000      0
5         0               2           95000      1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Refund          10 non-null     int64
 1   Marital_Status  10 non-null     int64
 2   Taxable_Income  10 non-null     int64
 3   Evade           10 non-null     int64
dtypes: int64(4)
memory usage: 400.0 bytes


In [5]:
data.columns

Index(['Refund', 'Marital_Status', 'Taxable_Income', 'Evade'], dtype='object')

In [10]:
features = data[['Refund', 'Marital_Status', 'Taxable_Income']]
target = data[['Evade']]

In [11]:
from sklearn.naive_bayes import GaussianNB
from sklearn.utils.validation import column_or_1d
classifier = GaussianNB()
classifier.fit(features, column_or_1d(target))

GaussianNB()

In [12]:
import numpy as np
classifier.score(features, np.array(target))

1.0

In [13]:
class_names = classifier.classes_
class_names

array([0, 1])

In [14]:
# X_check = [["No", "Married", 120000],
#            ["No", "Single", 90000]]
X_check = [[0, 1, 120000],
           [0, 0, 90000]]
y_result = classifier.predict(X_check)
y_result

array([0, 1])

In [15]:
import pickle
pkl_file = "pickle_classifier.pkl"
with open(pkl_file, 'wb') as file:
    pickle.dump(classifier, file)

In [16]:
with open(pkl_file, 'rb') as file:
    pickle_classifier = pickle.load(file)

In [17]:
x_check = [[0, 0, 75000]]
y_result_ = pickle_classifier.predict(x_check)
y_result_

array([0])